ismoktify/urls.py
from django.urls import path, include
from . import views
from .views import ArticleCreateView, CoursesListView, CourseCreateView, TestCreateView, TestDetailView, QuestionDetailView, TestResulListView
app_name = 'ismoktify'
urlpatterns = [
    path('', views.index, name='index'),
    path('newarticle/', ArticleCreateView.as_view(), name='new_article'),
    path('courses/', CoursesListView.as_view(), name='course_list'),
    path('courses/<str:course_name>', views.course_view, name='course_detail'),
    path('courses/<str:course_name>/<int:article_id>', views.article_view, name='article_detail'),
    path('courses/<str:course_name>/<int:article_id>/edit', views.article_edit_view, name='article_edit'),
    path('new_course', CourseCreateView.as_view(), name='new_course'),
    path('courses/<str:course_name>/new_test/', TestCreateView.as_view(), name='new_test'),
    path('new_test/<int:pk>', TestDetailView.as_view(), name='test_detail'),
    path('new_question/<int:pk>', QuestionDetailView.as_view(), name='question_detail'),
    path('delete_answer/<int:pk>', views.answer_delete, name='answer_delete'),
    path('delete_question/<int:pk>', views.question_delete, name='question_delete'),
    path('test_generator/<int:pk>', views.unique_test, name='test_generator'),
    path('quiz_time/<int:pk>', views.quiz_time, name='quiz_time'),
    path('teacher', TestResulListView.as_view(), name='teacher_list'),
]

ismoktify_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ismoktify.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ismoktify/models.py
from django_quill.fields import QuillField
from django.db import models
from django.conf import settings


class Course(models.Model):
    name = models.CharField(max_length=100, primary_key=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200)
    content = QuillField()


class QuillPost(models.Model):
    content = QuillField()


class Test(models.Model):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=180)
    number_of_easy_questions = models.IntegerField()
    number_of_medium_questions = models.IntegerField()
    number_of_hard_questions = models.IntegerField()
    def __str__(self):
        return self.title
    
    
class Question(models.Model):
    test = models.ForeignKey(
        Test, on_delete=models.CASCADE, blank=True, null=True)
    content = models.CharField(max_length=180)
    weight = models.IntegerField()
    

    def __str__(self):
        return self.content
    
    
class Answer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, blank=True, null=True)
    content = models.CharField(max_length=180)
    is_true = models.BooleanField()
    
    def __str__(self):
        return self.content
    

class UniqueTest(models.Model):
    questions = models.ManyToManyField(Question)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

class TestResult(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.FloatField()
    

ismoktify/forms.py
from django import forms
from django.forms import ModelForm
from django_quill.forms import QuillFormField
from .models import Course, Article, Test, Question, Answer, UniqueTest


class QuillFieldForm(forms.Form):
    content = QuillFormField()


class ArticleForm(forms.ModelForm):
    template = 'ismoktify/new_article.html'

    class Meta:
        model = Article
        fields = ['course', 'title', 'content']
        template = 'ismoktify/new_article.html'

class CourseForm(forms.ModelForm):
    template = 'ismoktify/new_course.html'
    
    class Meta:
        model = Course
        fields = ['name']
        template = 'ismoktify/new_course.html'
        
class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['course', 'title', 'number_of_easy_questions', 'number_of_medium_questions', 'number_of_hard_questions']
        
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['test', 'content', 'weight']
        labels = {
            'content': 'Question',
            'weight': 'Points / question'
        }    
        widgets = {'test': forms.HiddenInput()}
    
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content', 'is_true']
        labels = {
            'content': 'Answer',
            'is_true': 'Correct answer'
        }
        widgets = {'question': forms.HiddenInput()}

ismoktify/views.py
from .forms import QuillFieldForm, ArticleForm, QuestionForm, AnswerForm
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormMixin
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from .models import Article, Course, Test, Question, Answer, UniqueTest, TestResult
import random


def index(request):
    return render(request, 'ismoktify/index.html')


class ArticleCreateView(CreateView):
    model = Article
    fields = ['course', 'title', 'content']

    def get_success_url(self) -> str:
        return reverse('ismoktify:course_detail', kwargs={'course_name': Article.objects.latest('title').course.name})


class CoursesListView(ListView):
    model = Course
    template_name = 'ismoktify/course_list.html'


def course_view(request, course_name):
    course = get_object_or_404(Course, pk=course_name)
    articles = Article.objects.filter(course=course_name)
    context = {
        'course': course,
        'articles': articles
    }
    return render(request, 'ismoktify/course_detail.html', context=context)


def article_view(request, article_id, course_name):
    article = get_object_or_404(Article, pk=article_id)
    context = {
        'article': article
    }
    return render(request, 'ismoktify/article_detail.html', context=context)


def article_edit_view(request, article_id, course_name):
    article = Article.objects.get(id=article_id)
    article_copy = Article.objects.get(id=article_id)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article.course = article_copy.course
            form.save()
            return redirect('ismoktify:article_detail', article.course.name, article.id)
    else:
        form = ArticleForm(instance=article)

    return render(request, 'ismoktify/article_edit.html', {'form': form})


class CourseCreateView(CreateView):
    model = Course
    fields = ['name']
    success_url = reverse_lazy('ismoktify:course_list')


class TestCreateView(CreateView):
    model = Test
    fields = ['course', 'title', 'number_of_easy_questions',
              'number_of_medium_questions', 'number_of_hard_questions']

    def get_success_url(self):
        return reverse('ismoktify:test_detail', kwargs={'pk': Test.objects.latest('id').id})


class TestDetailView(FormMixin, DetailView):
    model = Test
    template_name = 'ismoktify/test_detail.html'
    form_class = QuestionForm

    def get_success_url(self):
        return reverse('ismoktify:question_detail', kwargs={'pk': Question.objects.latest('id').id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.test = self.object
        form.save()
        return super(TestDetailView, self).form_valid(form)


class QuestionDetailView(FormMixin, DetailView):
    model = Question
    template_name = 'ismoktify/question_detail.html'
    form_class = AnswerForm

    def get_success_url(self):
        return reverse('ismoktify:question_detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.question = self.object
        form.save()
        return super(QuestionDetailView, self).form_valid(form)


def answer_delete(request, pk):
    query = Answer.objects.get(id=pk)
    link = query.question.id
    query.delete()
    return (redirect('ismoktify:question_detail', link))


def question_delete(request, pk):
    query = Question.objects.get(id=pk)
    link = query.test.id
    query.delete()
    return (redirect('ismoktify:test_detail', link))


def unique_test(request, pk):
    test_model = Test.objects.get(id=pk)
    available_easy_questions = list(
        Question.objects.filter(test=test_model).filter(weight=1))
    availible_medium_question = list(
        Question.objects.filter(test=test_model).filter(weight=2))
    availible_hard_question = list(
        Question.objects.filter(test=test_model).filter(weight=3))
    random_easy_questions = random.sample(
        available_easy_questions, test_model.number_of_easy_questions)
    random_medium_questions = random.sample(
        availible_medium_question, test_model.number_of_medium_questions)
    random_hard_questions = random.sample(
        availible_hard_question, test_model.number_of_hard_questions)
    arranged_test = UniqueTest(user=request.user)
    arranged_test.save()
    for question in random_easy_questions:
        arranged_test.questions.add(question)
    for question in random_medium_questions:
        arranged_test.questions.add(question)
    for question in random_hard_questions:
        arranged_test.questions.add(question)
    arranged_test.save()
    return(redirect('ismoktify:quiz_time', arranged_test.id))

def quiz_time(request, pk):
    unique_test = UniqueTest.objects.get(id=pk)
    if request.method == 'POST':
        answers = []
        data = request.POST 
        for question in unique_test.questions.all():
            if str(question.id) in data:
                answers.append(data[str(question.id)])
            else:
                answers.append(None)
        score = answers.count("True") / len(answers) * 10
        result_model = TestResult(user=request.user, score=score)
        result_model.save()
        return render(request, 'ismoktify/result.html', {'score':score})
    else:
        return render(request, 'ismoktify/uniquetest_detail.html', {'uniquetest':unique_test})

class TestResulListView(ListView):
    model = TestResult
    paginate_by = 50

ismoktify/templates/ismoktify/article_detail.html
{% extends 'ismoktify/base.html' %}
{% block title %}Courses{% endblock %}
{% block active_course_list%} active{% endblock %}
{% block content %}
<br>
<div style="width: 80vw; margin: 0 auto">
    <div class="d-flex flex-row">
    <h1>{{ article.title }}<h1>
    <a class="btn btn-outline-warning" href='{{ article.id }}/edit' role="button">Edit</a>
    </div>
    <hr>
    {{article.content.html|safe}}
</div>
{% endblock %}

ismoktify/templates/ismoktify/article_edit.html
{% extends 'ismoktify/base.html' %}
{% block head %}
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{% endblock %}
{% block content %}
<div style="width: 80vw; margin: 0 auto">
<form action="" method="POST">{% csrf_token %}
    {{ form.title }}
    {{ form.content }}
    <br>
    <button type="submit" class="btn btn-warning submit-button">Update article</button>
</form>
</div>
{% endblock %}

ismoktify/templates/ismoktify/article_form.html
{% extends 'ismoktify/base.html' %}
{% load crispy_forms_tags %}
{% block head %}
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{% endblock %}
{% block content %}
<div style="width: 80vw; margin:0 auto;">
<form action="" method="POST">{% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-warning submit-button">Create article</button>
</form>
</div>
{% endblock %}

ismoktify/templates/ismoktify/base.html
<!DOCTYPE html>
{% load static %} {% load ismoktify_extras %}
<html lang="en">
  <head>
    {%block head %}{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'ismoktify/images/favicon.ico' %}"
    />
    <title>{% block title %}Išmoktify{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% if request.user|has_group:"Teacher" %}
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      {% elif request.user|has_group:"Student" %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        {% else %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    {% endif %}
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'ismoktify:index' %}">Išmoktify</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user|has_group:"Teacher" %}
            <li class="nav-item">
              <a class="nav-link{% block active_new_article %}{% endblock %}" href="{% url 'ismoktify:new_article' %}">New article</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link{% block active_course_list %}{% endblock %}" href="{% url 'ismoktify:course_list' %}">Courses</a>
            </li>
            {% if request.user|has_group:"Teacher" %}
            <li class="nav-item">
              <a class="nav-link{% block active_teacher %}{% endblock %}" href="{% url 'ismoktify:teacher_list' %}"
                >Teacher</a
              >
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div id="content">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

ismoktify/templates/ismoktify/course_detail.html
{% extends 'ismoktify/base.html' %}
{% load static %} {% load ismoktify_extras %}
{% block title %}Courses{% endblock %}
{% block active_course_list%} active{% endblock %}
{% block content %}
    <div style="width: 80vw; margin: 0 auto">
    <h1>{{course.name}}</h1>
        <ul class="list-group">
        {% for article in articles %}
            <li class="list-group-item"><a style="font-size: 1.7em" class="link-dark" href='{{article.course.name}}/{{article.id}}'>{{article.title}}</a></li>
        {% endfor %}
        </ul>
        {% if request.user|has_group:"Teacher" %}
        <div class="d-flex flex-row">
        {% if course.test_set.all.count > 0 %}
        <a class="btn btn-warning" href='{% url "ismoktify:test_detail" course.test_set.all.0.id %}' role="button" style='margin-right:40px'>{{ course.test_set.all.0.title }}</a>
        {% else %}
        <a  class="btn btn-warning" href='{{ course.name }}/new_test' role='button' style='margin-right:40px'>Add Test<a>
        {% endif %}
        <a class="btn btn-warning" href='{% url "ismoktify:new_article"%}' role='button'>New article<a>
        </div>
        {% endif %}
        {% if request.user|has_group:"Student" %}
        {{course.test_set.id}}
        <a  class="btn btn-success" href="{% url 'ismoktify:test_generator' course.test_set.all.0.id  %}" role='button' style='margin-right:40px'>Quiz<a>
        {% endif %}
    </div>

{% endblock %}

ismoktify/templates/ismoktify/course_form.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{%endblock %} 
{% block content %}
    <h1 style="width: 80vw; margin: 0 auto">New Course</h1>
    <br />
    <div style="width: 80vw; margin: 0 auto">
    <form action="" method="POST">
        {% csrf_token %} {{ form|crispy }}
        <button type="submit" class="btn btn-warning submit-button">
        Create new Course
        </button>
    </form>
    </div>
{% endblock %}

ismoktify/templates/ismoktify/course_list.html
{% extends 'ismoktify/base.html' %}
{% load static %} {% load ismoktify_extras %}
{% block title %}Courses{% endblock %}
{% block active_course_list%} active{% endblock %}
{% block content %}
<div style="width: 80vw; margin:0 auto;">
    <h1> List of availible courses</h1>
    {% if course_list %}
        <ul class="list-group">
            {% for course in course_list %}
                <li class="list-group-item">
                    <a class="link-dark" href="{{ course.name }}">{{ course.name }}<a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no availible courses</p>
    {% endif %}
    {% if request.user|has_group:"Teacher" %}
    <a href="{% url 'ismoktify:new_course' %}">
        <button type="submit" class="btn btn-warning submit-button">Create new Course</button>
    </a>
    </div>
    {% endif %}
{% endblock %}

ismoktify/templates/ismoktify/index.html
{% extends "ismoktify/base.html" %}
{% load static %} {% load ismoktify_extras %} {% block index_act %} active{% endblock %}
{% block content %}

<h1> Basic web site that helps you to learn new stuff :) <h1>
{% endblock %}

ismoktify/templates/ismoktify/question_detail.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{%endblock %} 
{% block content %}
<div style="width: 80vw; margin: 0 auto">
    <h1>{{question.content}}</h1>

    <form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-warning submit-button">
        Add answer
    </button>
    </form>
    <ul class="list-group">
        {% for answer in question.answer_set.all %}
            <li class="list-group-item" style="color:{%if answer.is_true%}green{% else %}red{%endif%}">{{answer.content}} <a style="color:red" href="{% url  'ismoktify:answer_delete' answer.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg></a></li>
        {% endfor %}
        </ul>
    <br>
    <a class="btn btn-warning" href='{% url "ismoktify:test_detail" question.test.id %}' role="button">Back to Qestions</a>
</div>
{% endblock %}

ismoktify/templates/ismoktify/result.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{%endblock %} 
{% block content %}
<div style="width: 80vw; margin: 0 auto">
    <h1>YOUR SCORE: {{score}}</h1>
{% endblock %}

ismoktify/templates/ismoktify/test_detail.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{%endblock %} 
{% block content %}
<div style="width: 80vw; margin: 0 auto">
    <h1>{{test.title}}</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-warning submit-button">
            Add question
        </button>
        </form>
    <ol class="list-group">
    {% for question in test.question_set.all %}
        <li class="list-group-item"><a style="color:black" href="{% url 'ismoktify:question_detail' question.id %}">{{question.content}}<a><a style="color:red" href="{% url 'ismoktify:question_delete' question.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg></a></li>
    {% endfor %}
    </oi>

</div>
{% endblock %}

ismoktify/templates/ismoktify/test_form.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{%endblock %} 
{% block content %}
<div style="width: 80vw; margin: 0 auto">
    <form action="" method="POST">
    <h1>New Test</h1>
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-warning submit-button">
        Next
    </button>
    </form>
</div>
{% endblock %}

ismoktify/templates/ismoktify/testresult_list.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_teacher %} active{%endblock %} 
{% block content %}
<div style="width: 80vw; margin: 0 auto">
    <table class="table">
    {% for result in object_list %}
        <tr>
        <th>{{result.user}}</th>
        <th>{{result.score}}</th>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

ismoktify/templates/ismoktify/uniquetest_detail.html
{% extends 'ismoktify/base.html' %} 
{% load crispy_forms_tags %} 
{% block head %} 
    {{ form.media }}
{% endblock %}
{% block active_new_article %} active{%endblock %} 
{% block content %}
<div style="width: 80vw; margin: 0 auto">
    <form action="" method="POST">{% csrf_token %}
    {% for question in uniquetest.questions.all %}
    <fieldset>
        <legend>{{question.content}}</legend>
        {% for answer in question.answer_set.all %}
        <input type="checkbox"  class="form-check-input" name="{{answer.question.id}}"" id="id_{{ answer.id }}" value="{{ answer.is_true }}">
        <label for="id_{{ answer.id }}">{{ answer.content }}</label>
        <br>
        {% endfor %}
        <hr>
    </fieldset>
    {% endfor %}
    <button type="submit" class="btn btn-primary submit-button">Submit</button>
    </form>
{% endblock %}